// ============================================================
// KORI — Decoration
//
// Koru (the unfurling fern frond, for new life and growth) and poutama
// (the stepped pattern, for striving and attainment), generated rather
// than drawn by hand so the curve stays smooth at any size.
//
// These are respectful nods to the visual language, not authentic
// kowhaiwhai. Anything going in front of whanau should have its patterns
// chosen with Rauawaawa, not generated by a build script.
// ============================================================

(function () {

const SVG_NS = 'http://www.w3.org/2000/svg';

// A logarithmic spiral, drawn as a closed shape whose width is full at
// the open end and tapers to nothing at the curled tip.
function koruPath(opts) {
    const o = Object.assign({ turns: 1.75, a: 4.5, b: 0.30, width: 34, steps: 90 }, opts || {});
    const pts = [];
    for (let i = 0; i <= o.steps; i++) {
        const t = i / o.steps;
        const th = t * o.turns * Math.PI * 2;
        const r = o.a * Math.exp(o.b * th);
        pts.push({ x: r * Math.cos(th), y: r * Math.sin(th), w: o.width * Math.pow(1 - t, 1.5) });
    }
    const left = [], right = [];
    for (let i = 0; i < pts.length; i++) {
        const p = pts[i];
        const q = pts[Math.min(i + 1, pts.length - 1)];
        const s = pts[Math.max(i - 1, 0)];
        const dx = q.x - s.x, dy = q.y - s.y;
        const L = Math.hypot(dx, dy) || 1;
        const nx = -dy / L, ny = dx / L;
        left.push([p.x + nx * p.w / 2, p.y + ny * p.w / 2]);
        right.push([p.x - nx * p.w / 2, p.y - ny * p.w / 2]);
    }
    const ring = left.concat(right.reverse());
    return 'M' + ring.map(p => p[0].toFixed(1) + ' ' + p[1].toFixed(1)).join(' L') + ' Z';
}

// Poutama: a solid staircase climbing to a peak and back down again.
// Drawn as one continuous outline — separate columns of rising height
// read as a bar chart, not as steps.
function poutamaPath(steps, step) {
    let d = 'M0 0';
    for (let i = 0; i < steps; i++) d += ' h' + step + ' v' + (-step);
    for (let i = 0; i < steps; i++) d += ' v' + step + ' h' + step;
    return d + ' Z';
}

function svg(attrs, children) {
    const el = document.createElementNS(SVG_NS, 'svg');
    for (const k in attrs) el.setAttribute(k, attrs[k]);
    children.forEach(c => el.appendChild(c));
    return el;
}

function path(d, attrs) {
    const el = document.createElementNS(SVG_NS, 'path');
    el.setAttribute('d', d);
    for (const k in attrs) el.setAttribute(k, attrs[k]);
    return el;
}

function mount(container) {
    if (!container) return;
    container.innerHTML = '';
    const k = koruPath();

    // Two koru, set diagonally opposite so the page reads as balanced
    // rather than decorated in one corner.
    [['tl', 'translate(96,104) rotate(-20)'],
     ['br', 'translate(-96,-104) rotate(160)']].forEach(([pos, tf]) => {
        const s = svg({ class: 'koru koru--' + pos, viewBox: '-150 -150 300 300', 'aria-hidden': 'true' },
                      [path(k, { fill: 'currentColor', transform: 'scale(1.9)' })]);
        container.appendChild(s);
    });

    // Poutama has to tile, not stretch: one run of steps pulled across the
    // whole width just reads as scattered blocks. An SVG <pattern> repeats
    // the tile at its true proportions however wide the screen is.
    const STEP = 20, COLS = 4;
    const tileW = COLS * STEP * 2, tileH = COLS * STEP;
    ['top', 'bottom'].forEach((pos, i) => {
        const el = document.createElementNS(SVG_NS, 'svg');
        el.setAttribute('class', 'poutama poutama--' + pos);
        el.setAttribute('aria-hidden', 'true');
        el.innerHTML =
            '<defs><pattern id="poutama' + i + '" width="' + tileW + '" height="' + tileH +
            '" patternUnits="userSpaceOnUse">' +
            '<path d="' + poutamaPath(COLS, STEP) +
            '" fill="currentColor" transform="translate(0,' + tileH + ')"/>' +
            '</pattern></defs>' +
            '<rect width="100%" height="100%" fill="url(#poutama' + i + ')"/>';
        container.appendChild(el);
    });
}

window.KoriDecor = { mount: mount, koruPath: koruPath, poutamaPath: poutamaPath };

})();
